
CREATE TABLE GENERO (
     ID NUMBER GENERATED ALWAYS AS IDENTITY,
    NOMBRE VARCHAR2(100) NOT NULL,
        CONSTRAINT PK_GENERO PRIMARY KEY (ID)
);
CREATE TABLE ARTISTA (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    NOMBRE VARCHAR2(100) NOT NULL,
    GENERO_ID NUMBER NOT NULL,
    CONSTRAINT PK_ARTISTA PRIMARY KEY (ID),
    CONSTRAINT FK_ARTISTA_GENERO FOREIGN KEY (GENERO_ID) REFERENCES GENERO(ID)
);
CREATE TABLE ALBUM (
     ID NUMBER GENERATED ALWAYS AS IDENTITY,
    ARTISTA_ID NUMBER NOT NULL,
    TITULO VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_ALBUM PRIMARY KEY (ID),
    CONSTRAINT FK_ALBUM_ARTISTA FOREIGN KEY (ARTISTA_ID) 
        REFERENCES ARTISTA(ID)
);
CREATE TABLE CANCION (
     ID NUMBER GENERATED ALWAYS AS IDENTITY,
    ALBUM_ID NUMBER,
    ARTISTA_ID NUMBER NOT NULL,
    NUMERO_TRACK NUMBER NOT NULL,
    NOMBRE VARCHAR2(100) NOT NULL,
    DURACION_MINUTOS NUMBER(5,2) NOT NULL,
    CONSTRAINT PK_CANCION PRIMARY KEY (ID),
    CONSTRAINT FK_CANCION_ALBUM FOREIGN KEY (ALBUM_ID) 	
        REFERENCES ALBUM(ID),
    CONSTRAINT FK_CANCION_ARTISTA FOREIGN KEY (ARTISTA_ID) 
        REFERENCES ARTISTA(ID)
);
CREATE TABLE USUARIO (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    CORREO VARCHAR2(100) NOT NULL UNIQUE,
    NOMBRES VARCHAR2(100) NOT NULL,
    APELLIDOS VARCHAR2(100) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    TIPO_CUENTA NUMBER(1) NOT NULL CHECK (TIPO_CUENTA IN (0, 1)),
    TARJETA_CREDITO VARCHAR2(20),
    CONSTRAINT PK_USUARIO PRIMARY KEY (ID)
);
CREATE TABLE USUARIO_GENERO (
	ID NUMBER GENERATED ALWAYS AS IDENTITY,
    USUARIO_ID NUMBER,
    GENERO_ID NUMBER,
    CONSTRAINT PK_USUARIO_GENERO PRIMARY KEY (ID),
    CONSTRAINT FK_UG_USUARIO FOREIGN KEY (USUARIO_ID) 
        REFERENCES USUARIO(ID),
    CONSTRAINT FK_UG_GENERO FOREIGN KEY (GENERO_ID) 
        REFERENCES GENERO(ID)
);


insert into genero (nombre) values ('Pop');

select nombre from GENERO


select user from dual;
SHOW CON_NAME;


SELECT table_name, tablespace_name 
FROM user_tables;



DROP TABLE USUARIO_GENERO CASCADE CONSTRAINTS;

DROP TABLE CANCION CASCADE CONSTRAINTS;

DROP TABLE ALBUM CASCADE CONSTRAINTS;

DROP TABLE ARTISTA CASCADE CONSTRAINTS;

DROP TABLE USUARIO CASCADE CONSTRAINTS;

DROP TABLE GENERO CASCADE CONSTRAINTS;

STARTUP;
ALTER PLUGGABLE DATABASE miPDB OPEN;
SELECT NAME, OPEN_MODE
FROM V$PDBS;